### ISSUE TITLE
Demo page failed to choose source types other than File from disk

### ISSUE THREAD

**Issue by Zmnortal** [yusitnikov/fix-webm-duration#23]
I want to try features on demo page. When I selected source type like Video from camera the page directly crash. And
<img width="623" alt="image" src="https://github.com/yusitnikov/fix-webm-duration/assets/49364497/26a33c45-f82c-4c0e-84b7-2c98a1b1c365">
here is the stack look like.

**Comment by yusitnikov** [comment]
Sorry, I assumed that everybody has support for the vp9 codec, but looks like it's not the case.
Added option to choose the codec, and changed the default to auto-detection.
