### ISSUE TITLE
suggestion: return a promise

### ISSUE THREAD

**Issue by lr-mjaouen** [yusitnikov/fix-webm-duration#3]
Hey, thank you it seems to work like a charm!
Just a suggestion, maybe it would be better to return directly a promise instead of a callback?

**Comment by yusitnikov** [comment]
Glad that my small library helped you :)
Initially, I didn't return a promise because this library is targeting old browsers where promises are not supported. But you're welcome to open a pull request with returning a promise object when it's available.

**Comment by lr-mjaouen** [comment]
To be honest I don't intend to spend more time on this, I hope this will be fixed by itself soon.
I need to take a look at https://github.com/legokichi/ts-ebml it might solve other possible issues I could encounter among this one but probably too heavier for the moment.
Thank you again, have a nice day!

**Comment by yusitnikov** [comment]
Update: added promise support at v1.0.1 - skip the callback argument and the function will return a promise
