### ISSUE TITLE
does this fix also video/x-matroska blobs?

### ISSUE THREAD

**Issue by eatalien** [yusitnikov/fix-webm-duration#8]
@yusitnikov thanks for this library.
Question: MediaRecorder on Chrome for MacOS defaults to video/x-matroska blob type. This library seems to be fixing those blobs too. Do you know if matroska mime type is supported by this library? If not all the matroska types are supported, does the library support the one created by Chrome on MacOS?

**Comment by yusitnikov** [comment]
Didn't test that
